name: integration
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
      - update-nixpkgs-*
  pull_request:
env:
  GO_VERSION: '1.22'
  CONMON_BINARY: /usr/local/bin/conmon  # from: scripts/github-actions-setup
permissions:
  contents: read

jobs:
  test-binaries:
    strategy:
      fail-fast: false
      matrix:
        run:
          - runner: ubuntu-latest
            arch: amd64
          - runner: actuated-arm64-4cpu-16gb
            arch: arm64
    name: binaries / ${{ matrix.run.arch }}
    runs-on: ${{ matrix.run.runner }}
    steps:
      - uses: alexellis/arkade-get@d543d47741e9217ba62ff0214444add9a35825f3
        with:
          crane: latest
          print-summary: false
      - name: Install vmmeter
        run: crane export --platform linux/${{ matrix.run.arch }} ghcr.io/openfaasltd/vmmeter:latest | sudo tar -xvf - -C /usr/local/bin
      - uses: self-actuated/vmmeter-action@c7e2162e39294a810cab647cacc215ecd68a44f6
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-test-binaries-${{ matrix.run.arch }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('test') }}
      - run: scripts/github-actions-packages
      - run: make all test-binaries
      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: test-binaries-${{ matrix.run.arch }}
          path: |
            bin/crio
            bin/pinns
            test/checkcriu/checkcriu
            test/checkseccomp/checkseccomp
            test/copyimg/copyimg
            test/nri/nri.test

  integration:
    needs: test-binaries
    strategy:
      fail-fast: false
      matrix:
        run:
          - name: critest / conmon
            arch: amd64
            runner: ubuntu-latest
            runtimeType: oci
            critest: 1
            userns: 0
            jobs: 1
            timeout: 10
          - name: critest / conmon
            arch: arm64
            runner: actuated-arm64-8cpu-32gb
            runtimeType: oci
            critest: 1
            userns: 0
            timeout: 10
          - name: critest / conmon-rs
            arch: amd64
            runner: ubuntu-latest
            runtimeType: pod
            critest: 1
            userns: 0
            jobs: 1
            timeout: 10
          - name: critest / conmon-rs
            arch: arm64
            runner: actuated-arm64-8cpu-32gb
            runtimeType: pod
            critest: 1
            userns: 0
            jobs: 1
            timeout: 10
          - name: integration / conmon
            arch: amd64
            runner: ubuntu-latest
            runtimeType: oci
            critest: 0
            userns: 0
            jobs: 2
            timeout: 120
          - name: integration / conmon
            arch: arm64
            runner: actuated-arm64-8cpu-32gb
            runtimeType: oci
            critest: 0
            userns: 0
            jobs: 2
            timeout: 120
          - name: integration / conmon-rs
            arch: amd64
            runner: ubuntu-latest
            runtimeType: pod
            critest: 0
            userns: 1
            jobs: 2
            timeout: 120
          - name: integration / conmon-rs
            arch: arm64
            runner: actuated-arm64-8cpu-32gb
            runtimeType: pod
            critest: 0
            userns: 1
            jobs: 2
            timeout: 120
          - name: integration / userns
            arch: amd64
            runner: ubuntu-latest
            runtimeType: oci
            critest: 0
            userns: 1
            jobs: 2
            timeout: 120
          - name: integration / userns
            arch: arm64
            runner: actuated-arm64-8cpu-32gb
            runtimeType: oci
            critest: 0
            userns: 1
            jobs: 2
            timeout: 120
    name: ${{ matrix.run.name }} / ${{ matrix.run.arch }}
    runs-on: ${{ matrix.run.runner }}
    timeout-minutes: ${{ matrix.run.timeout }}
    steps:
      - uses: alexellis/arkade-get@d543d47741e9217ba62ff0214444add9a35825f3
        with:
          crane: latest
          print-summary: false
      - name: Install vmmeter
        run: crane export --platform linux/${{ matrix.run.arch }} ghcr.io/openfaasltd/vmmeter:latest | sudo tar -xvf - -C /usr/local/bin
      - uses: self-actuated/vmmeter-action@c7e2162e39294a810cab647cacc215ecd68a44f6
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ matrix.run.name }}-${{ matrix.run.arch }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('scripts/versions') }}
      - uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0
      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: test-binaries-${{ matrix.run.arch }}
      - name: Fix artifact permissions
        run: |
          chmod +x \
            bin/crio \
            bin/pinns \
            test/checkcriu/checkcriu \
            test/checkseccomp/checkseccomp \
            test/copyimg/copyimg \
            test/nri/nri.test
      - run: scripts/github-actions-packages
      - run: scripts/github-actions-setup
      - run: sudo -E test/test_runner.sh
        env:
          JOBS: ${{ matrix.run.jobs }}
          RUN_CRITEST: ${{ matrix.run.critest }}
          RUNTIME_TYPE: ${{ matrix.run.runtimeType }}
          TEST_USERNS: ${{ matrix.run.userns }}
